---
index_last_selected: 0
presets:
- name: デフォルト
  hostname: irc.trpg.net
  port: 6667
  password: 
  encoding: UTF-8
  nick: BCDice
  channel: "#Dice_Test"
  quit_message: さようなら
  game_system_id: DiceBot
