# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: bcdice_irc.proto for package 'bcdice_irc_proto'

require 'grpc'
require 'bcdice_irc_pb'

module BcdiceIrcProto
  module BCDiceIRCService
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'bcdice_irc_proto.BCDiceIRCService'

      # Version はBCDice IRCおよび関連プログラムのバージョン情報を返す。
      rpc :Version, VersionRequest, VersionResponse
      # Stop はサービスを停止する。
      rpc :Stop, StopRequest, StopResponse
    end

    Stub = Service.rpc_stub_class
  end
end
