# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bcdice_irc.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("bcdice_irc.proto", :syntax => :proto3) do
    add_message "bcdice_irc_proto.VersionRequest" do
    end
    add_message "bcdice_irc_proto.VersionResponse" do
      optional :bcdice, :string, 1
      optional :bcdice_irc, :string, 2
    end
    add_message "bcdice_irc_proto.StopRequest" do
    end
    add_message "bcdice_irc_proto.StopResponse" do
    end
  end
end

module BcdiceIrcProto
  VersionRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("bcdice_irc_proto.VersionRequest").msgclass
  VersionResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("bcdice_irc_proto.VersionResponse").msgclass
  StopRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("bcdice_irc_proto.StopRequest").msgclass
  StopResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("bcdice_irc_proto.StopResponse").msgclass
end
